highlight:
  anchorLineNos: false
  codeFences: true
  guessSyntax: false
  hl_Lines: ""
  hl_inline: false
  lineAnchors: ""
  lineNoStart: 1
  lineNos: false
  lineNumbersInTable: true
  noClasses: true
  style: catppuccin-macchiato
  tabWidth: 4
  wrapperClass: highlight
