imports:
  - path: github.com/rozard-genset/corest
  - path: github.com/rozard-genset/course
  - path: github.com/almuhdilkarim/webdev-basic
  - path: github.com/almuhdilkarim/mariadb-basic
  - path: github.com/almuhdilkarim/libarch-basic